# Generated by Django 4.1.5 on 2023-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_player_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
