# Generated by Django 4.1.5 on 2023-02-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_player_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="done",
        ),
    ]
