# Generated by Django 4.1.5 on 2023-02-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_player_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
