# Generated by Django 4.1.5 on 2023-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_ques_delete_quesmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ques",
            name="direction",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
